import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import NextUI from "@/components/NextUIProvider/NextUIProvider";
import Footer from "@/components/Footer/Footer";

const prompt = Prompt({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={prompt.className}>
                <NavigationBar />
                <NextUI>{children}</NextUI>
                <Footer />
            </body>
        </html>
    );
}
